version: "3.8"

services:
  postgres: 
   image: postgres
   environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=auctions
      - POSTGRES_USERNAME=postgres
   ports:
      - 5432:5432 
   volumes:
     - pgdata:/var/lib/postgresql/data 
     
volumes:
  pgdata: